version: '3.3'
services:

  # Running postgres on port 5432
  postgres:
    image: postgres:11.1
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: unless-stopped

  # Running pgAdmin on port 5555
  # Note: On deployment you need to set the server configs after login into the pgAdmin client. Use the postgres
  #       configs for this one
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - 5555:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - SERVER_MODE=True
    restart: unless-stopped

  # A service container to
  dbs-configurator:
    build:
      context: './dbs-configurator'
    container_name: dbs-configurator
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - GF_PG_USER=${GF_PG_USER}
      - GF_PG_PASSWORD=${GF_PG_PASSWORD}
    restart: unless-stopped

  # Running grafana on port 8080
  grafana:
    build:
      context: './grafana'
    container_name: grafana
    depends_on:
      - postgres
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_PG_USER=${GF_PG_USER}
      - GF_PG_PASSWORD=${GF_PG_PASSWORD}
    ports:
      - '8080:3000'
    user: "root"
    volumes:
      - grafana_storage:/var/lib/grafana
    restart: unless-stopped


  # Data analytics and NLP worker 
  analyzer:
    build:
      context: './analyzer'
    container_name: analyzer
    depends_on:
      - postgres
      - dbs-configurator
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped

  # Data analytics and NLP worker
  scraper:
    build:
      context: './scraper'
    container_name: scraper
    depends_on:
      - postgres
      - dbs-configurator
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped

volumes:
  dbdata:
  grafana_storage:
