version: '3.3'
services:

  # Running postgres on port 5432
  postgres:
    image: postgres:11.1
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

  # A service container to
  dbs-configurator:
    build:
      context: './dbs-configurator'
    container_name: dbs-configurator
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  # Running grafana on port 8080
  grafana:
    build:
      context: './grafana'
    container_name: grafana
    depends_on:
      - postgres
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_PG_USER=${GF_PG_USER}
      - GF_PG_PASSWORD=${GF_PG_PASSWORD}
    ports:
      - '8080:3000'
    user: "root"
    volumes:
      - grafana_storage:/var/lib/grafana


  # Data analytics and NLP worker 
  analyzer:
    build:
      context: './analyzer'
    container_name: analyzer
    depends_on:
      - postgres
      - dbs-configurator
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  # Data analytics and NLP worker
  scraper:
    build:
      context: './scraper'
    container_name: scraper
    depends_on:
      - postgres
      - dbs-configurator
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  dbdata:
  grafana_storage:
