apiVersion: 1

datasources:

  - name: Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: postgres
    user: $GF_PG_USER
    isDefault: true
    version: 1
    editable: true
    secureJsonData:
      password: $GF_PG_PASSWORD
    jsonData:
      sslmode: disable
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1000   # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: false

  - name: Prometheus
    url: http://prometheus:9090
    type: prometheus
    access: proxy
    jsonData:
      graphiteVersion: "1.1"
      tlsAuth: false
      tlsAuthWithCACert: false
    editable: true