{
 "title": "CDU Chairman Candidates Sentiment",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Sentiment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CDU Merz - Sentiment Over Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n\tCASE\n\t\tWHEN (udfs.udf_value IS NULL) THEN hdr.source_date\n\t\tELSE to_date(\"substring\"((udfs.udf_value)::text, 1, 10), 'YYYY-MM-DD'::text)\n\tEND AS time,\n\tSUM(sentiment_value/ (error_value * error_value )) / SUM(1 / (error_value * error_value)) AS \"Sentiment1 Error Weighted\",\n\tAVG(sentiment_value) AS \"Sentiment2 Simple Average\"\nFROM news_meta_data.analyzer1_result AS rslt, \n\t\tnews_meta_data.article_body AS bdy,\n\t\tnews_meta_data.article_header AS hdr,\n\t\tnews_meta_data.comment AS cmt\n\tLEFT JOIN\n\t\tnews_meta_data.udf_values as udfs\n\t\tON udfs.object_id = cmt.id\nWHERE \n\t\trslt.sub_id = 1 AND\n\t\trslt.comment_id = cmt.id AND\n\t\tcmt.article_body_id = bdy.id AND\n\t\thdr.id = bdy.article_id AND\n\t\tudfs.object_type = 2 AND\n\t\tudfs.udf_id = 4 AND\n\t\tcmt.body ilike '% merz%'\n\nGROUP BY time\nORDER BY time DESC\n"
      }
     ]
    },
    {
     "title": "CDU Laschet - Sentiment Over Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n\tCASE\n\t\tWHEN (udfs.udf_value IS NULL) THEN hdr.source_date\n\t\tELSE to_date(\"substring\"((udfs.udf_value)::text, 1, 10), 'YYYY-MM-DD'::text)\n\tEND AS time,\n\tSUM(sentiment_value/ (error_value * error_value )) / SUM(1 / (error_value * error_value)) AS \"Sentiment1 Error Weighted\",\n\tAVG(sentiment_value) AS \"Sentiment2 Simple Average\"\nFROM news_meta_data.analyzer1_result AS rslt, \n\t\tnews_meta_data.article_body AS bdy,\n\t\tnews_meta_data.article_header AS hdr,\n\t\tnews_meta_data.comment AS cmt\n\tLEFT JOIN\n\t\tnews_meta_data.udf_values as udfs\n\t\tON udfs.object_id = cmt.id\nWHERE \n\t\trslt.sub_id = 1 AND\n\t\trslt.comment_id = cmt.id AND\n\t\tcmt.article_body_id = bdy.id AND\n\t\thdr.id = bdy.article_id AND\n\t\tudfs.object_type = 2 AND\n\t\tudfs.udf_id = 4 AND\n\t\tcmt.body ilike '% laschet%'\n\nGROUP BY time\nORDER BY time DESC\n"
      }
     ]
    },
    {
     "title": "CDU Röttgen - Sentiment Over Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n\tCASE\n\t\tWHEN (udfs.udf_value IS NULL) THEN hdr.source_date\n\t\tELSE to_date(\"substring\"((udfs.udf_value)::text, 1, 10), 'YYYY-MM-DD'::text)\n\tEND AS time,\n\tSUM(sentiment_value/ (error_value * error_value )) / SUM(1 / (error_value * error_value)) AS \"Sentiment1 Error Weighted\",\n\tAVG(sentiment_value) AS \"Sentiment2 Simple Average\"\nFROM news_meta_data.analyzer1_result AS rslt, \n\t\tnews_meta_data.article_body AS bdy,\n\t\tnews_meta_data.article_header AS hdr,\n\t\tnews_meta_data.comment AS cmt\n\tLEFT JOIN\n\t\tnews_meta_data.udf_values as udfs\n\t\tON udfs.object_id = cmt.id\nWHERE \n\t\trslt.sub_id = 1 AND\n\t\trslt.comment_id = cmt.id AND\n\t\tcmt.article_body_id = bdy.id AND\n\t\thdr.id = bdy.article_id AND\n\t\tudfs.object_type = 2 AND\n\t\tudfs.udf_id = 4 AND\n\t\t(cmt.body ilike '% röttgen%' OR cmt.body ilike '% roettgen%')\n\nGROUP BY time\nORDER BY time DESC\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Comments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CDU Merz - # Comments Over Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n\tCASE\n\t\tWHEN (udfs.udf_value IS NULL) THEN hdr.source_date\n\t\tELSE to_date(\"substring\"((udfs.udf_value)::text, 1, 10), 'YYYY-MM-DD'::text)\n\tEND AS time,\n\tcount(cmt.id) as \"# Comments\"\nFROM news_meta_data.analyzer1_result AS rslt, \n\t\tnews_meta_data.article_body AS bdy,\n\t\tnews_meta_data.article_header AS hdr,\n\t\tnews_meta_data.comment AS cmt\n\tLEFT JOIN\n\t\tnews_meta_data.udf_values as udfs\n\t\tON udfs.object_id = cmt.id\nWHERE \n\t\trslt.sub_id = 1 AND\n\t\trslt.comment_id = cmt.id AND\n\t\tcmt.article_body_id = bdy.id AND\n\t\thdr.id = bdy.article_id AND\n\t\tudfs.object_type = 2 AND\n\t\tudfs.udf_id = 4 AND\n\t\tcmt.body ilike '% merz%'\n\nGROUP BY time\nORDER BY time DESC\n"
      }
     ]
    },
    {
     "title": "CDU Laschet - # Comments Over Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n\tCASE\n\t\tWHEN (udfs.udf_value IS NULL) THEN hdr.source_date\n\t\tELSE to_date(\"substring\"((udfs.udf_value)::text, 1, 10), 'YYYY-MM-DD'::text)\n\tEND AS time,\n\tcount(cmt.id) as \"# Comments\"\nFROM news_meta_data.analyzer1_result AS rslt, \n\t\tnews_meta_data.article_body AS bdy,\n\t\tnews_meta_data.article_header AS hdr,\n\t\tnews_meta_data.comment AS cmt\n\tLEFT JOIN\n\t\tnews_meta_data.udf_values as udfs\n\t\tON udfs.object_id = cmt.id\nWHERE \n\t\trslt.sub_id = 1 AND\n\t\trslt.comment_id = cmt.id AND\n\t\tcmt.article_body_id = bdy.id AND\n\t\thdr.id = bdy.article_id AND\n\t\tudfs.object_type = 2 AND\n\t\tudfs.udf_id = 4 AND\n\t\tcmt.body ilike '% laschet%'\n\nGROUP BY time\nORDER BY time DESC\n"
      }
     ]
    },
    {
     "title": "CDU Röttgen - # Comments Over Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n\tCASE\n\t\tWHEN (udfs.udf_value IS NULL) THEN hdr.source_date\n\t\tELSE to_date(\"substring\"((udfs.udf_value)::text, 1, 10), 'YYYY-MM-DD'::text)\n\tEND AS time,\n\tcount(cmt.id) as \"# Comments\"\nFROM news_meta_data.analyzer1_result AS rslt, \n\t\tnews_meta_data.article_body AS bdy,\n\t\tnews_meta_data.article_header AS hdr,\n\t\tnews_meta_data.comment AS cmt\n\tLEFT JOIN\n\t\tnews_meta_data.udf_values as udfs\n\t\tON udfs.object_id = cmt.id\nWHERE \n\t\trslt.sub_id = 1 AND\n\t\trslt.comment_id = cmt.id AND\n\t\tcmt.article_body_id = bdy.id AND\n\t\thdr.id = bdy.article_id AND\n\t\tudfs.object_type = 2 AND\n\t\tudfs.udf_id = 4 AND\n\t\t(cmt.body ilike '% röttgen%' OR cmt.body ilike '% roettgen%')\n\nGROUP BY time\nORDER BY time DESC\n"
      }
     ]
    }
   ]
  }
 ]
}