{
 "title": "Covid-19 Sentiment",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "news_outlet",
    "label": "News Outlet",
    "query": "SELECT source FROM news_meta_data.source_header"
   },
   {
    "name": "sub_id",
    "label": "Analyzer ID",
    "query": "SELECT DISTINCT sub_id FROM news_meta_data.analyzer1_result"
   }
  ]
 },
 "panels": [
  { "title": "Topic: Covid-19", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Articles Analyzed for \"$news_outlet\" in range",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(DISTINCT ah.id)\nFROM\n  news_meta_data.article_header ah\n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\n  INNER JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  INNER JOIN news_meta_data.comment ct ON ah.id = ct.article_body_id\n  INNER JOIN news_meta_data.analyzer1_result a1r ON ct.id = a1r.comment_id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet)\n  AND a1r.sub_id = $sub_id\n  AND (ab.body ILIKE '% covid19%' OR ab.body ILIKE '% covid%' OR ab.body ILIKE '% covid-19%' OR ab.body ILIKE '% coronavirus%')"
    }
   ]
  },
  {
   "title": "Comments Analyzed for \"$news_outlet\" in range",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(DISTINCT ct.id)\nFROM\n  news_meta_data.article_header ah\n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\n  INNER JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  INNER JOIN news_meta_data.comment ct ON ab.id = ct.article_body_id\n  INNER JOIN news_meta_data.analyzer1_result a1r ON ct.id = a1r.comment_id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet)\n  AND a1r.sub_id = $sub_id\n  AND (ab.body ILIKE '% covid19%' OR ab.body ILIKE '% covid%' OR ab.body ILIKE '% covid-19%' OR ab.body ILIKE '% coronavirus%')"
    }
   ]
  },
  {
   "title": "Comment Sentiment over Time for: $news_outlet",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ah.source_date AS time,\n  SUM(a1r.sentiment_value/ (a1r.error_value * a1r.error_value )) / SUM(1 / (a1r.error_value * a1r.error_value)) AS \"Sentiment1 Error Weighted\",\n  AVG(a1r.sentiment_value) AS \"Sentiment2 Simple Average\"\nFROM\n  news_meta_data.article_header ah\n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\n  INNER JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  INNER JOIN news_meta_data.comment ct ON ab.id = ct.article_body_id\n  INNER JOIN news_meta_data.analyzer1_result a1r ON ct.id = a1r.comment_id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet)\n  AND a1r.sub_id = $sub_id\n  AND (ab.body ILIKE '% covid19%' OR ab.body ILIKE '% covid%' OR ab.body ILIKE '% covid-19%' OR ab.body ILIKE '% coronavirus%')\nGROUP BY\n  ah.source_date\nORDER BY\n  1"
    }
   ]
  },
  { "title": "Topic: Lockdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Articles Analyzed for \"$news_outlet\" in range",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(DISTINCT ah.id)\nFROM\n  news_meta_data.article_header ah\n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\n  INNER JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  INNER JOIN news_meta_data.comment ct ON ab.id = ct.article_body_id\n  INNER JOIN news_meta_data.analyzer1_result a1r ON ct.id = a1r.comment_id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet)\n  AND a1r.sub_id = $sub_id\n  AND (ab.body ILIKE '% lockdown%')"
    }
   ]
  },
  {
   "title": "Comments Analyzed for \"$news_outlet\" in range",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(DISTINCT ct.id)\nFROM\n  news_meta_data.article_header ah\n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\n  INNER JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  INNER JOIN news_meta_data.comment ct ON ab.id = ct.article_body_id\n  INNER JOIN news_meta_data.analyzer1_result a1r ON ct.id = a1r.comment_id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet)\n  AND a1r.sub_id = $sub_id\n  AND (ab.body ILIKE '% lockdown%')"
    }
   ]
  },
  {
   "title": "Comment Sentiment over Time for: $news_outlet",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ah.source_date AS time,\n  SUM(a1r.sentiment_value/ (a1r.error_value * a1r.error_value )) / SUM(1 / (a1r.error_value * a1r.error_value)) AS \"Sentiment1 Error Weighted\",\n  AVG(a1r.sentiment_value) AS \"Sentiment2 Simple Average\"\nFROM\n  news_meta_data.article_header ah\n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\n  INNER JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  INNER JOIN news_meta_data.comment ct ON ab.id = ct.article_body_id\n  INNER JOIN news_meta_data.analyzer1_result a1r ON ct.id = a1r.comment_id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet)\n  AND a1r.sub_id = $sub_id\n  AND (ab.body ILIKE '% lockdown%')\nGROUP BY\n  ah.source_date\nORDER BY\n  1"
    }
   ]
  },
  { "title": "Topic: Impfung/Vakzin", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Articles Analyzed for \"$news_outlet\" in range",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(DISTINCT ah.id)\nFROM\n  news_meta_data.article_header ah\n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\n  INNER JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  INNER JOIN news_meta_data.comment ct ON ab.id = ct.article_body_id\n  INNER JOIN news_meta_data.analyzer1_result a1r ON ct.id = a1r.comment_id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet)\n  AND a1r.sub_id = $sub_id\n  AND (ab.body ILIKE '% impfung%' OR ab.body ILIKE '% vakzin%' OR ab.body ILIKE '% impfen%' OR ab.body ILIKE '% impfstoff%')"
    }
   ]
  },
  {
   "title": "Comments Analyzed for \"$news_outlet\" in range",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(DISTINCT ct.id)\nFROM\n  news_meta_data.article_header ah\n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\n  INNER JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  INNER JOIN news_meta_data.comment ct ON ab.id = ct.article_body_id\n  INNER JOIN news_meta_data.analyzer1_result a1r ON ct.id = a1r.comment_id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet)\n  AND a1r.sub_id = $sub_id\n  AND (ab.body ILIKE '% impfung%' OR ab.body ILIKE '% vakzin%' OR ab.body ILIKE '% impfen%' OR ab.body ILIKE '% impfstoff%')"
    }
   ]
  },
  {
   "title": "Comment Sentiment over Time for: $news_outlet",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ah.source_date AS time,\n  SUM(a1r.sentiment_value/ (a1r.error_value * a1r.error_value )) / SUM(1 / (a1r.error_value * a1r.error_value)) AS \"Sentiment1 Error Weighted\",\n  AVG(a1r.sentiment_value) AS \"Sentiment2 Simple Average\"\nFROM\n  news_meta_data.article_header ah\n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\n  INNER JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  INNER JOIN news_meta_data.comment ct ON ab.id = ct.article_body_id\n  INNER JOIN news_meta_data.analyzer1_result a1r ON ct.id = a1r.comment_id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet)\n  AND a1r.sub_id = $sub_id\n  AND (ab.body ILIKE '% impfung%' OR ab.body ILIKE '% vakzin%' OR ab.body ILIKE '% impfen%' OR ab.body ILIKE '% impfstoff%')\nGROUP BY\n  ah.source_date\nORDER BY\n  1"
    }
   ]
  }
 ]
}