{
 "title": "Covid-19 Statistics",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "news_outlet",
    "label": "News Outlet",
    "query": "SELECT source FROM news_meta_data.source_header"
   },
   {
    "name": "nlp_model",
    "label": "NLP Model",
    "query": "    SELECT\n      'Ensemble' AS nlp_model\n    UNION ALL\n    SELECT\n      'Multilanguage Bert' AS nlp_model\n    UNION ALL\n    SELECT\n      'German Bert' AS nlp_model"
   }
  ]
 },
 "panels": [
  { "title": "General Covid-19 Sentiment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Comment Sentiment",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ah.source_date AS Time,\n  --SUM(a1r.sentiment_value/ (a1r.error_value * a1r.error_value )) / SUM(1 / (a1r.error_value * a1r.error_value)) AS \"Sentiment1 Error Weighted\",\n  AVG(a1r.sentiment_value) AS \"Sentiment Simple Average\"\nFROM\n  news_meta_data.article_header ah\n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\n  INNER JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  INNER JOIN news_meta_data.comment ct ON ab.id = ct.article_body_id\n  INNER JOIN news_meta_data.analyzer1_result a1r ON ct.id = a1r.comment_id\n  LEFT JOIN \n    (\n    SELECT\n      1 AS id,\n      'Ensemble' AS nlp_model\n    UNION ALL\n    SELECT\n      2 AS id,\n      'Multilanguage Bert' AS nlp_model\n    UNION ALL\n    SELECT\n      3 AS id,\n      'German Bert' AS nlp_model\n    ) nlp ON a1r.sub_id = nlp.id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet)\n  AND nlp.nlp_model = '$nlp_model'\n  AND (ct.body ILIKE '% covid%' OR ct.body ILIKE '% coronavirus%' OR ct.body ILIKE '% covid19%' OR ct.body ILIKE '% sars-cov-2%'  OR ct.body ILIKE '% corona%')\nGROUP BY\n  ah.source_date\nORDER BY\n  1"
    }
   ]
  },
  {
   "title": "# Comments",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ah.source_date AS Time,\n  COUNT(DISTINCT ct.id) AS \"# Comments\"\nFROM\n  news_meta_data.article_header ah\n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\n  INNER JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  INNER JOIN news_meta_data.comment ct ON ab.id = ct.article_body_id\n  INNER JOIN news_meta_data.analyzer1_result a1r ON ct.id = a1r.comment_id\n  LEFT JOIN \n    (\n    SELECT\n      1 AS id,\n      'Ensemble' AS nlp_model\n    UNION ALL\n    SELECT\n      2 AS id,\n      'Multilanguage Bert' AS nlp_model\n    UNION ALL\n    SELECT\n      3 AS id,\n      'German Bert' AS nlp_model\n    ) nlp ON a1r.sub_id = nlp.id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet)\n  AND nlp.nlp_model = '$nlp_model'\n  AND (ct.body ILIKE '% covid%' OR ct.body ILIKE '% coronavirus%' OR ct.body ILIKE '% covid19%' OR ct.body ILIKE '% sars-cov-2%'  OR ct.body ILIKE '% corona%')\nGROUP BY\n  ah.source_date\nORDER BY\n  1"
    }
   ]
  },
  { "title": "Vakzin Sentiment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Comment Sentiment",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ah.source_date AS Time,\n  --SUM(a1r.sentiment_value/ (a1r.error_value * a1r.error_value )) / SUM(1 / (a1r.error_value * a1r.error_value)) AS \"Sentiment1 Error Weighted\",\n  AVG(a1r.sentiment_value) AS \"Sentiment Simple Average\"\nFROM\n  news_meta_data.article_header ah\n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\n  INNER JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  INNER JOIN news_meta_data.comment ct ON ab.id = ct.article_body_id\n  INNER JOIN news_meta_data.analyzer1_result a1r ON ct.id = a1r.comment_id\n  LEFT JOIN \n    (\n    SELECT\n      1 AS id,\n      'Ensemble' AS nlp_model\n    UNION ALL\n    SELECT\n      2 AS id,\n      'Multilanguage Bert' AS nlp_model\n    UNION ALL\n    SELECT\n      3 AS id,\n      'German Bert' AS nlp_model\n    ) nlp ON a1r.sub_id = nlp.id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet)\n  AND nlp.nlp_model = '$nlp_model'\n  AND (ct.body ILIKE '% impfung%' OR ct.body ILIKE '% vakzin%' OR ct.body ILIKE '% impfen%' OR ct.body ILIKE '% impfstoff%'  OR ct.body ILIKE '% impfstof%')\nGROUP BY\n  ah.source_date\nORDER BY\n  1"
    }
   ]
  },
  {
   "title": "# Comments",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ah.source_date AS Time,\n  COUNT(DISTINCT ct.id) AS \"# Comments\"\nFROM\n  news_meta_data.article_header ah\n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\n  INNER JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  INNER JOIN news_meta_data.comment ct ON ab.id = ct.article_body_id\n  INNER JOIN news_meta_data.analyzer1_result a1r ON ct.id = a1r.comment_id\n  LEFT JOIN \n    (\n    SELECT\n      1 AS id,\n      'Ensemble' AS nlp_model\n    UNION ALL\n    SELECT\n      2 AS id,\n      'Multilanguage Bert' AS nlp_model\n    UNION ALL\n    SELECT\n      3 AS id,\n      'German Bert' AS nlp_model\n    ) nlp ON a1r.sub_id = nlp.id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet)\n  AND nlp.nlp_model = '$nlp_model'\n  AND (ct.body ILIKE '% impfung%' OR ct.body ILIKE '% vakzin%' OR ct.body ILIKE '% impfen%' OR ct.body ILIKE '% impfstoff%'  OR ct.body ILIKE '% impfstof%')\nGROUP BY\n  ah.source_date\nORDER BY\n  1"
    }
   ]
  },
  { "title": "Lockdown Sentiment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Comment Sentiment",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ah.source_date AS Time,\n  --SUM(a1r.sentiment_value/ (a1r.error_value * a1r.error_value )) / SUM(1 / (a1r.error_value * a1r.error_value)) AS \"Sentiment1 Error Weighted\",\n  AVG(a1r.sentiment_value) AS \"Sentiment Simple Average\"\nFROM\n  news_meta_data.article_header ah\n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\n  INNER JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  INNER JOIN news_meta_data.comment ct ON ab.id = ct.article_body_id\n  INNER JOIN news_meta_data.analyzer1_result a1r ON ct.id = a1r.comment_id\n  LEFT JOIN \n    (\n    SELECT\n      1 AS id,\n      'Ensemble' AS nlp_model\n    UNION ALL\n    SELECT\n      2 AS id,\n      'Multilanguage Bert' AS nlp_model\n    UNION ALL\n    SELECT\n      3 AS id,\n      'German Bert' AS nlp_model\n    ) nlp ON a1r.sub_id = nlp.id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet)\n  AND nlp.nlp_model = '$nlp_model'\n  AND (ct.body ILIKE '% lockdown%')\nGROUP BY\n  ah.source_date\nORDER BY\n  1"
    }
   ]
  },
  {
   "title": "# Comments",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ah.source_date AS Time,\n  COUNT(DISTINCT ct.id) AS \"# Comments\"\nFROM\n  news_meta_data.article_header ah\n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\n  INNER JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  INNER JOIN news_meta_data.comment ct ON ab.id = ct.article_body_id\n  INNER JOIN news_meta_data.analyzer1_result a1r ON ct.id = a1r.comment_id\n  LEFT JOIN \n    (\n    SELECT\n      1 AS id,\n      'Ensemble' AS nlp_model\n    UNION ALL\n    SELECT\n      2 AS id,\n      'Multilanguage Bert' AS nlp_model\n    UNION ALL\n    SELECT\n      3 AS id,\n      'German Bert' AS nlp_model\n    ) nlp ON a1r.sub_id = nlp.id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet)\n  AND nlp.nlp_model = '$nlp_model'\n  AND (ct.body ILIKE '% lockdown%')\nGROUP BY\n  ah.source_date\nORDER BY\n  1"
    }
   ]
  },
  { "title": "Raw Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "# Articles",
   "type": "stat",
   "description": "Covid-19 (or synonyms) mentioned in article text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  COUNT(DISTINCT ah.id)\nFROM  \n  news_meta_data.article_header ah\n  INNER JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet)\n  AND (ab.body ILIKE '% covid%' OR ab.body ILIKE '% coronavirus%' OR ab.body ILIKE '% covid19%' OR ab.body ILIKE '% sars-cov-2%'  OR ab.body ILIKE '% corona%')\n"
    }
   ]
  },
  {
   "title": "# Comments",
   "type": "stat",
   "description": "Covid-19 (or synonyms) mentioned in article text",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  COUNT(DISTINCT c.id)\nFROM \n  news_meta_data.article_header ah \n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\n  LEFT JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  LEFT JOIN news_meta_data.comment c ON c.article_body_id = ab.id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet)\n  AND (ab.body ILIKE '% covid%' OR ab.body ILIKE '% coronavirus%' OR ab.body ILIKE '% covid19%' OR ab.body ILIKE '% sars-cov-2%'  OR ab.body ILIKE '% corona%')"
    }
   ]
  },
  {
   "title": "Articles per Day",
   "type": "timeseries",
   "description": "Covid-19 (or synonyms) mentioned in article text",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n  source_date::TIMESTAMP AS time, \n  COUNT(DISTINCT ah.id) AS \"# Articles\"\nFROM  \n  news_meta_data.article_header ah\n  INNER JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet)\n  AND (ab.body ILIKE '% covid%' OR ab.body ILIKE '% coronavirus%' OR ab.body ILIKE '% covid19%' OR ab.body ILIKE '% sars-cov-2%'  OR ab.body ILIKE '% corona%')\nGROUP BY \n  1\nORDER BY \n  1"
    }
   ]
  },
  {
   "title": "Article-Comments Per Day",
   "type": "timeseries",
   "description": "Covid-19 (or synonyms) mentioned in article text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n  source_date::TIMESTAMP AS time, \n  COUNT(DISTINCT c.id) AS \"# Comments\"\nFROM \n  news_meta_data.article_header ah \n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\n  LEFT JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  LEFT JOIN news_meta_data.comment c ON c.article_body_id = ab.id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet)\n  AND (ab.body ILIKE '% covid%' OR ab.body ILIKE '% coronavirus%' OR ab.body ILIKE '% covid19%' OR ab.body ILIKE '% sars-cov-2%'  OR ab.body ILIKE '% corona%')\nGROUP BY \n  1\nORDER BY \n  1"
    }
   ]
  }
 ]
}