{
 "title": "Double Comment Sentiment Analysis",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "comment_search_1", "label": "Comment Search (Left)", "query": "Wetter" },
   { "name": "comment_search_2", "label": "Comment Search (Right)", "query": " Schnee" }
  ]
 },
 "panels": [
  {
   "title": "Sentiment Comparison",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sentiment Over Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n\tCASE\n\t\tWHEN (udfs.udf_value IS NULL) THEN hdr.source_date\n\t\tELSE to_date(\"substring\"((udfs.udf_value)::text, 1, 10), 'YYYY-MM-DD'::text)\n\tEND AS time,\n\tSUM(sentiment_value/ (error_value * error_value )) / SUM(1 / (error_value * error_value)) AS \"Sentiment1 Error Weighted\",\n\tAVG(sentiment_value) AS \"Sentiment2 Simple Average\"\nFROM news_meta_data.analyzer1_result AS rslt, \n\t\tnews_meta_data.article_body AS bdy,\n\t\tnews_meta_data.article_header AS hdr,\n\t\tnews_meta_data.comment AS cmt\n\tLEFT JOIN\n\t\tnews_meta_data.udf_values as udfs\n\t\tON udfs.object_id = cmt.id\nWHERE \n\t\trslt.sub_id = 1 AND\n\t\trslt.comment_id = cmt.id AND\n\t\tcmt.article_body_id = bdy.id AND\n\t\thdr.id = bdy.article_id AND\n\t\tudfs.object_type = 2 AND\n\t\tudfs.udf_id = 4 AND\n\t\tcmt.body ilike '% $comment_search_1%'\n\nGROUP BY time\nORDER BY time DESC\n"
      }
     ]
    },
    {
     "title": "Sentiment Over Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n\tCASE\n\t\tWHEN (udfs.udf_value IS NULL) THEN hdr.source_date\n\t\tELSE to_date(\"substring\"((udfs.udf_value)::text, 1, 10), 'YYYY-MM-DD'::text)\n\tEND AS time,\n\tSUM(sentiment_value/ (error_value * error_value )) / SUM(1 / (error_value * error_value)) AS \"Sentiment1 Error Weighted\",\n\tAVG(sentiment_value) AS \"Sentiment2 Simple Average\"\nFROM news_meta_data.analyzer1_result AS rslt, \n\t\tnews_meta_data.article_body AS bdy,\n\t\tnews_meta_data.article_header AS hdr,\n\t\tnews_meta_data.comment AS cmt\n\tLEFT JOIN\n\t\tnews_meta_data.udf_values as udfs\n\t\tON udfs.object_id = cmt.id\nWHERE \n\t\trslt.sub_id = 1 AND\n\t\trslt.comment_id = cmt.id AND\n\t\tcmt.article_body_id = bdy.id AND\n\t\thdr.id = bdy.article_id AND\n\t\tudfs.object_type = 2 AND\n\t\tudfs.udf_id = 4 AND\n\t\tcmt.body ilike '% $comment_search_2%'\n\nGROUP BY time\nORDER BY time DESC\n"
      }
     ]
    },
    {
     "title": "# Comments Over Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n\tCASE\n\t\tWHEN (udfs.udf_value IS NULL) THEN hdr.source_date\n\t\tELSE to_date(\"substring\"((udfs.udf_value)::text, 1, 10), 'YYYY-MM-DD'::text)\n\tEND AS time,\n\tcount(cmt.id) as \"# Comments\"\nFROM news_meta_data.analyzer1_result AS rslt, \n\t\tnews_meta_data.article_body AS bdy,\n\t\tnews_meta_data.article_header AS hdr,\n\t\tnews_meta_data.comment AS cmt\n\tLEFT JOIN\n\t\tnews_meta_data.udf_values as udfs\n\t\tON udfs.object_id = cmt.id\nWHERE \n\t\trslt.sub_id = 1 AND\n\t\trslt.comment_id = cmt.id AND\n\t\tcmt.article_body_id = bdy.id AND\n\t\thdr.id = bdy.article_id AND\n\t\tudfs.object_type = 2 AND\n\t\tudfs.udf_id = 4 AND\n\t\tcmt.body ilike '% $comment_search_1%'\n\nGROUP BY time\nORDER BY time DESC\n"
      }
     ]
    },
    {
     "title": "# Comments Over Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n\tCASE\n\t\tWHEN (udfs.udf_value IS NULL) THEN hdr.source_date\n\t\tELSE to_date(\"substring\"((udfs.udf_value)::text, 1, 10), 'YYYY-MM-DD'::text)\n\tEND AS time,\n\tcount(cmt.id) as \"# Comments\"\nFROM news_meta_data.analyzer1_result AS rslt, \n\t\tnews_meta_data.article_body AS bdy,\n\t\tnews_meta_data.article_header AS hdr,\n\t\tnews_meta_data.comment AS cmt\n\tLEFT JOIN\n\t\tnews_meta_data.udf_values as udfs\n\t\tON udfs.object_id = cmt.id\nWHERE \n\t\trslt.sub_id = 1 AND\n\t\trslt.comment_id = cmt.id AND\n\t\tcmt.article_body_id = bdy.id AND\n\t\thdr.id = bdy.article_id AND\n\t\tudfs.object_type = 2 AND\n\t\tudfs.udf_id = 4 AND\n\t\tcmt.body ilike '% $comment_search_2%'\n\nGROUP BY time\nORDER BY time DESC\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Comperative Analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Difference (Left and Right) Sentiment Over Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "WITH comment_1 AS (\nSELECT \n\tCASE\n\t\tWHEN (udfs.udf_value IS NULL) THEN hdr.source_date\n\t\tELSE to_date(\"substring\"((udfs.udf_value)::text, 1, 10), 'YYYY-MM-DD'::text)\n\tEND AS time,\n\tSUM(sentiment_value/ (error_value * error_value )) / SUM(1 / (error_value * error_value)) AS \"Sentiment1 Error Weighted\",\n\tAVG(sentiment_value) AS \"Sentiment2 Simple Average\"\nFROM news_meta_data.analyzer1_result AS rslt, \n\t\tnews_meta_data.article_body AS bdy,\n\t\tnews_meta_data.article_header AS hdr,\n\t\tnews_meta_data.comment AS cmt\n\tLEFT JOIN\n\t\tnews_meta_data.udf_values as udfs\n\t\tON udfs.object_id = cmt.id\nWHERE \n\t\trslt.sub_id = 1 AND\n\t\trslt.comment_id = cmt.id AND\n\t\tcmt.article_body_id = bdy.id AND\n\t\thdr.id = bdy.article_id AND\n\t\tudfs.object_type = 2 AND\n\t\tudfs.udf_id = 4 AND\n\t\tcmt.body ilike '% $comment_search_1%'\n\nGROUP BY time\nORDER BY time DESC\n),\ncomment_2 AS (\nSELECT \n\tCASE\n\t\tWHEN (udfs.udf_value IS NULL) THEN hdr.source_date\n\t\tELSE to_date(\"substring\"((udfs.udf_value)::text, 1, 10), 'YYYY-MM-DD'::text)\n\tEND AS time,\n\tSUM(sentiment_value/ (error_value * error_value )) / SUM(1 / (error_value * error_value)) AS \"Sentiment1 Error Weighted\",\n\tAVG(sentiment_value) AS \"Sentiment2 Simple Average\"\nFROM news_meta_data.analyzer1_result AS rslt, \n\t\tnews_meta_data.article_body AS bdy,\n\t\tnews_meta_data.article_header AS hdr,\n\t\tnews_meta_data.comment AS cmt\n\tLEFT JOIN\n\t\tnews_meta_data.udf_values as udfs\n\t\tON udfs.object_id = cmt.id\nWHERE \n\t\trslt.sub_id = 1 AND\n\t\trslt.comment_id = cmt.id AND\n\t\tcmt.article_body_id = bdy.id AND\n\t\thdr.id = bdy.article_id AND\n\t\tudfs.object_type = 2 AND\n\t\tudfs.udf_id = 4 AND\n\t\tcmt.body ilike '% $comment_search_2%'\n\nGROUP BY time\nORDER BY time DESC\n)\n\nSELECT\n  c1.time,\n  c1.\"Sentiment1 Error Weighted\" - c2.\"Sentiment1 Error Weighted\" AS \"Delta Sentiment1 Error Weighted\",\n  c1.\"Sentiment2 Simple Average\" - c2.\"Sentiment2 Simple Average\" AS \"Delta Sentiment2 Simple Average\"\nFROM\n  comment_1 c1\n  INNER JOIN comment_2 c2 ON c1.time = c2.time\nORDER BY \n  1 DESC\n\n"
      }
     ]
    },
    {
     "title": "Comment Ratio",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "WITH comment_1 AS (\nSELECT \n\tCASE\n\t\tWHEN (udfs.udf_value IS NULL) THEN hdr.source_date\n\t\tELSE to_date(\"substring\"((udfs.udf_value)::text, 1, 10), 'YYYY-MM-DD'::text)\n\tEND AS time,\n\tcount(cmt.id) as \"# Comments\"\nFROM news_meta_data.analyzer1_result AS rslt, \n\t\tnews_meta_data.article_body AS bdy,\n\t\tnews_meta_data.article_header AS hdr,\n\t\tnews_meta_data.comment AS cmt\n\tLEFT JOIN\n\t\tnews_meta_data.udf_values as udfs\n\t\tON udfs.object_id = cmt.id\nWHERE \n\t\trslt.sub_id = 1 AND\n\t\trslt.comment_id = cmt.id AND\n\t\tcmt.article_body_id = bdy.id AND\n\t\thdr.id = bdy.article_id AND\n\t\tudfs.object_type = 2 AND\n\t\tudfs.udf_id = 4 AND\n\t\tcmt.body ilike '% $comment_search_1%'\n\nGROUP BY time\nORDER BY time DESC\n),\ncomment_2 AS (\nSELECT \n\tCASE\n\t\tWHEN (udfs.udf_value IS NULL) THEN hdr.source_date\n\t\tELSE to_date(\"substring\"((udfs.udf_value)::text, 1, 10), 'YYYY-MM-DD'::text)\n\tEND AS time,\n\tcount(cmt.id) as \"# Comments\"\nFROM news_meta_data.analyzer1_result AS rslt, \n\t\tnews_meta_data.article_body AS bdy,\n\t\tnews_meta_data.article_header AS hdr,\n\t\tnews_meta_data.comment AS cmt\n\tLEFT JOIN\n\t\tnews_meta_data.udf_values as udfs\n\t\tON udfs.object_id = cmt.id\nWHERE \n\t\trslt.sub_id = 1 AND\n\t\trslt.comment_id = cmt.id AND\n\t\tcmt.article_body_id = bdy.id AND\n\t\thdr.id = bdy.article_id AND\n\t\tudfs.object_type = 2 AND\n\t\tudfs.udf_id = 4 AND\n\t\tcmt.body ilike '% $comment_search_2%'\n\nGROUP BY time\nORDER BY time DESC\n)\n\nSELECT\n  c1.time,\n  c1.\"# Comments\"/c2.\"# Comments\"::NUMERIC AS \"Comment1-Comment2-Ratio\"\nFROM\n  comment_1 c1\n  INNER JOIN comment_2 c2 ON c1.time = c2.time\nORDER BY \n  1 DESC"
      }
     ]
    }
   ]
  }
 ]
}