{
 "title": "New POC Dashboard",
 "time": { "from": "2019-12-31T23:00:00.000Z", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# Articles",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  COUNT(url)\nFROM \n  news_meta_data.article_header\n"
    }
   ]
  },
  {
   "title": "# Articles with Headlines",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  COUNT(headline)\nFROM \n  news_meta_data.article_header ah \n  LEFT JOIN news_meta_data.article_body ab ON ah.id = ab.article_id"
    }
   ]
  },
  {
   "title": "Article Frequency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  source_date::TIMESTAMP AS time, \n  COUNT(url)\nFROM \n  news_meta_data.article_header\nGROUP BY \n  1\nORDER BY \n  1"
    }
   ]
  },
  {
   "title": "Headline Frequency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  source_date::TIMESTAMP AS time, \n  COUNT(headline)\nFROM \n  news_meta_data.article_header ah \n  LEFT JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\nGROUP BY \n  1\nORDER BY \n  1"
    }
   ]
  },
  {
   "title": "# Comments",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  COUNT(url)\nFROM \n  news_meta_data.article_header ah \n  LEFT JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  LEFT JOIN news_meta_data.comment c ON c.article_body_id = ab.id"
    }
   ]
  },
  {
   "title": "Comments Per Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  source_date::TIMESTAMP AS time, \n  COUNT(url)\nFROM \n  news_meta_data.article_header ah \n  LEFT JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  LEFT JOIN news_meta_data.comment c ON c.article_body_id = ab.id\nGROUP BY \n  1\nORDER BY \n  1"
    }
   ]
  },
  {
   "title": "Covid-19 Related Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true
  },
  {
   "title": "# Articles",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  COUNT(url)\nFROM \n  news_meta_data.article_header\nWHERE \n  url ILIKE '%covid%' OR url ILIKE '%corona%'    \n"
    }
   ]
  },
  {
   "title": "# Articles with Headlines",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  COUNT(headline)\nFROM \n  news_meta_data.article_header ah \n  LEFT JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\nWHERE \n  ab.headline ILIKE '%covid%' OR ab.headline ILIKE '%corona%'  "
    }
   ]
  },
  {
   "title": "Article Frequency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  source_date::TIMESTAMP AS time, \n  COUNT(url)\nFROM \n  news_meta_data.article_header\nWHERE \n  url ILIKE '%covid%' OR url ILIKE '%corona%'  \nGROUP BY \n  1\nORDER BY \n  1"
    }
   ]
  },
  {
   "title": "Headline Frequency - Covid-19",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  source_date::TIMESTAMP AS time, \n  COUNT(headline)\nFROM \n  news_meta_data.article_header ah \n  LEFT JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\nWHERE \n  ab.headline ILIKE '%covid%' OR ab.headline ILIKE '%corona%'\nGROUP BY \n  1\nORDER BY \n  1"
    }
   ]
  },
  {
   "title": "# Comments",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  COUNT(url)\nFROM \n  news_meta_data.article_header ah \n  LEFT JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  LEFT JOIN news_meta_data.comment c ON c.article_body_id = ab.id\nWHERE \n  ab.headline ILIKE '%covid%' OR ab.headline ILIKE '%corona%'  "
    }
   ]
  },
  {
   "title": "Comments Per Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  source_date::TIMESTAMP AS time, \n  COUNT(url)\nFROM \n  news_meta_data.article_header ah \n  LEFT JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  LEFT JOIN news_meta_data.comment c ON c.article_body_id = ab.id\nWHERE \n  ab.headline ILIKE '%covid%' OR ab.headline ILIKE '%corona%'  \nGROUP BY \n  1\nORDER BY \n  1"
    }
   ]
  }
 ]
}