{
 "title": "News Outlet Statistics",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "news_outlet",
    "label": "News Outlet",
    "query": "SELECT source FROM news_meta_data.source_header"
   },
   {
    "name": "nlp_model",
    "label": "NLP Model",
    "query": "    SELECT\n      'Ensemble' AS nlp_model\n    UNION ALL\n    SELECT\n      'Multilanguage Bert' AS nlp_model\n    UNION ALL\n    SELECT\n      'German Bert' AS nlp_model"
   }
  ]
 },
 "panels": [
  {
   "title": "AVG Sentiment",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(a1r.sentiment_value) AS \"Sentiment Simple Average\"\nFROM\n  news_meta_data.article_header ah\n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\n  INNER JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  INNER JOIN news_meta_data.comment ct ON ab.id = ct.article_body_id\n  INNER JOIN news_meta_data.analyzer1_result a1r ON ct.id = a1r.comment_id\n  LEFT JOIN \n    (\n    SELECT\n      1 AS id,\n      'Ensemble' AS nlp_model\n    UNION ALL\n    SELECT\n      2 AS id,\n      'Multilanguage Bert' AS nlp_model\n    UNION ALL\n    SELECT\n      3 AS id,\n      'German Bert' AS nlp_model\n    ) nlp ON a1r.sub_id = nlp.id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet)\n  AND nlp.nlp_model = '$nlp_model'"
    }
   ]
  },
  {
   "title": "Comment Sentiment",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ah.source_date AS Time,\n  --SUM(a1r.sentiment_value/ (a1r.error_value * a1r.error_value )) / SUM(1 / (a1r.error_value * a1r.error_value)) AS \"Sentiment1 Error Weighted\",\n  AVG(a1r.sentiment_value) AS \"Sentiment Simple Average\"\nFROM\n  news_meta_data.article_header ah\n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\n  INNER JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  INNER JOIN news_meta_data.comment ct ON ab.id = ct.article_body_id\n  INNER JOIN news_meta_data.analyzer1_result a1r ON ct.id = a1r.comment_id\n  LEFT JOIN \n    (\n    SELECT\n      1 AS id,\n      'Ensemble' AS nlp_model\n    UNION ALL\n    SELECT\n      2 AS id,\n      'Multilanguage Bert' AS nlp_model\n    UNION ALL\n    SELECT\n      3 AS id,\n      'German Bert' AS nlp_model\n    ) nlp ON a1r.sub_id = nlp.id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet)\n  AND nlp.nlp_model = '$nlp_model'\nGROUP BY\n  ah.source_date\nORDER BY\n  1"
    }
   ]
  },
  {
   "title": "# Comments",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  COUNT(DISTINCT c.id)\nFROM \n  news_meta_data.article_header ah \n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\n  LEFT JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  LEFT JOIN news_meta_data.comment c ON c.article_body_id = ab.id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet)"
    }
   ]
  },
  {
   "title": "Comments Per Day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n  source_date::TIMESTAMP AS time, \n  COUNT(DISTINCT c.id) AS \"# Comments\"\nFROM \n  news_meta_data.article_header ah \n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\n  LEFT JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  LEFT JOIN news_meta_data.comment c ON c.article_body_id = ab.id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet)\nGROUP BY \n  1\nORDER BY \n  1"
    }
   ]
  },
  {
   "title": "# Articles",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  COUNT(DISTINCT ah.id)\nFROM \n  news_meta_data.article_header ah\n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet)\n"
    }
   ]
  },
  {
   "title": "Articles per Day",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n  source_date::TIMESTAMP AS time, \n  COUNT(DISTINCT ah.id) AS \"# Articles\"\nFROM  \n  news_meta_data.article_header ah\n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet)\nGROUP BY \n  1\nORDER BY \n  1"
    }
   ]
  }
 ]
}