{
 "title": "POC Dashboard",
 "time": { "from": "2019-12-31T23:00:00.000Z", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "AVG Articles per Day",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(\"# Articles per Day\")::NUMERIC\nFROM\n(\nSELECT \n  published_at AS time,\n  COUNT(DISTINCT url) AS \"# Articles per Day\"\nFROM \n  news_meta_data.articles\nWHERE \n  $__timeFilter(published_at)  \nGROUP BY \n  1\n) avg  \n"
    }
   ]
  },
  {
   "title": "# Articles in DBS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  COUNT(DISTINCT url) AS \"# Articles per Day\"\nFROM \n  news_meta_data.articles\nWHERE \n  $__timeFilter(published_at)"
    }
   ]
  },
  {
   "title": "AVG Articles per Day about Covid-19",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(\"# Articles per Day\")::NUMERIC\nFROM\n(\nSELECT \n  published_at AS time,\n  COUNT(DISTINCT url) AS \"# Articles per Day\"\nFROM \n  news_meta_data.articles\nWHERE \n  $__timeFilter(published_at) AND (headline ILIKE '%covid%' OR headline ILIKE '%corona%')\nGROUP BY \n  1\n) avg  \n"
    }
   ]
  },
  {
   "title": "# Articles in DBS about Covid-19",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  COUNT(DISTINCT url) AS \"# Articles per Day\"\nFROM \n  news_meta_data.articles\nWHERE \n  $__timeFilter(published_at) AND (headline ILIKE '%covid%' OR headline ILIKE '%corona%')"
    }
   ]
  },
  {
   "title": "# Articles per Day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  published_at AS time,\n  COUNT(DISTINCT url) AS \"# Articles per Day\"\nFROM \n  news_meta_data.articles\nWHERE \n  $__timeFilter(published_at)\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "# Articles per Day about Covid-19",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  published_at AS time,\n  COUNT(DISTINCT url) AS \"# Articles per Day\"\nFROM \n  news_meta_data.articles\nWHERE \n  $__timeFilter(published_at) AND (headline ILIKE '%covid%' OR headline ILIKE '%corona%')\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Article Meta Data",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT * FROM news_meta_data.articles WHERE $__timeFilter(published_at) ORDER BY published_at DESC"
    }
   ]
  },
  {
   "title": "Article Meta Data about Covid-19",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT * FROM news_meta_data.articles WHERE   $__timeFilter(published_at) AND (headline ILIKE '%covid%' OR headline ILIKE '%corona%') ORDER BY published_at DESC"
    }
   ]
  }
 ]
}