{
 "title": "Sentiment Comperative Analysis",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "comment_key_word_left", "label": "Comment Search (Left)", "query": "Wetter" },
   {
    "name": "news_outlet_left",
    "label": "News Outlet (Left)",
    "query": "SELECT source FROM news_meta_data.source_header"
   },
   {
    "name": "nlp_model_left",
    "label": "NLP Model (Left)",
    "query": "    SELECT\n      'Ensemble' AS nlp_model\n    UNION ALL\n    SELECT\n      'Multilanguage Bert' AS nlp_model\n    UNION ALL\n    SELECT\n      'German Bert' AS nlp_model"
   },
   { "name": "comment_key_word_right", "label": "Comment Search (Right)", "query": "Schnee" },
   {
    "name": "news_outlet_right",
    "label": "News Outlet (Right)",
    "query": "SELECT source FROM news_meta_data.source_header"
   },
   {
    "name": "nlp_model_right",
    "label": "NLP Model (Right)",
    "query": "    SELECT\n      'Ensemble' AS nlp_model\n    UNION ALL\n    SELECT\n      'Multilanguage Bert' AS nlp_model\n    UNION ALL\n    SELECT\n      'German Bert' AS nlp_model"
   }
  ]
 },
 "panels": [
  { "title": "Sentiment Comparison", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Comment Sentiment",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ah.source_date AS Time,\n  --SUM(a1r.sentiment_value/ (a1r.error_value * a1r.error_value )) / SUM(1 / (a1r.error_value * a1r.error_value)) AS \"Sentiment1 Error Weighted\",\n  AVG(a1r.sentiment_value) AS \"Sentiment Simple Average\"\nFROM\n  news_meta_data.article_header ah\n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\n  INNER JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  INNER JOIN news_meta_data.comment ct ON ab.id = ct.article_body_id\n  INNER JOIN news_meta_data.analyzer1_result a1r ON ct.id = a1r.comment_id\n  LEFT JOIN \n    (\n    SELECT\n      1 AS id,\n      'Ensemble' AS nlp_model\n    UNION ALL\n    SELECT\n      2 AS id,\n      'Multilanguage Bert' AS nlp_model\n    UNION ALL\n    SELECT\n      3 AS id,\n      'German Bert' AS nlp_model\n    ) nlp ON a1r.sub_id = nlp.id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet_left)\n  AND nlp.nlp_model = '$nlp_model_left'\n  AND ct.body ILIKE '% $comment_key_word_left%'\nGROUP BY\n  ah.source_date\nORDER BY\n  1"
    }
   ]
  },
  {
   "title": "Comment Sentiment",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ah.source_date AS Time,\n  --SUM(a1r.sentiment_value/ (a1r.error_value * a1r.error_value )) / SUM(1 / (a1r.error_value * a1r.error_value)) AS \"Sentiment1 Error Weighted\",\n  AVG(a1r.sentiment_value) AS \"Sentiment Simple Average\"\nFROM\n  news_meta_data.article_header ah\n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\n  INNER JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  INNER JOIN news_meta_data.comment ct ON ab.id = ct.article_body_id\n  INNER JOIN news_meta_data.analyzer1_result a1r ON ct.id = a1r.comment_id\n  LEFT JOIN \n    (\n    SELECT\n      1 AS id,\n      'Ensemble' AS nlp_model\n    UNION ALL\n    SELECT\n      2 AS id,\n      'Multilanguage Bert' AS nlp_model\n    UNION ALL\n    SELECT\n      3 AS id,\n      'German Bert' AS nlp_model\n    ) nlp ON a1r.sub_id = nlp.id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet_right)\n  AND nlp.nlp_model = '$nlp_model_right'\n  AND ct.body ILIKE '% $comment_key_word_right%'\nGROUP BY\n  ah.source_date\nORDER BY\n  1"
    }
   ]
  },
  {
   "title": "# Comments",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ah.source_date AS Time,\n  COUNT(DISTINCT ct.id) AS \"# Comments\"\nFROM\n  news_meta_data.article_header ah\n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\n  INNER JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  INNER JOIN news_meta_data.comment ct ON ab.id = ct.article_body_id\n  INNER JOIN news_meta_data.analyzer1_result a1r ON ct.id = a1r.comment_id\n  LEFT JOIN \n    (\n    SELECT\n      1 AS id,\n      'Ensemble' AS nlp_model\n    UNION ALL\n    SELECT\n      2 AS id,\n      'Multilanguage Bert' AS nlp_model\n    UNION ALL\n    SELECT\n      3 AS id,\n      'German Bert' AS nlp_model\n    ) nlp ON a1r.sub_id = nlp.id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet_left)\n  AND nlp.nlp_model = '$nlp_model_left'\n  AND ct.body ILIKE '% $comment_key_word_left%'\nGROUP BY\n  ah.source_date\nORDER BY\n  1"
    }
   ]
  },
  {
   "title": "# Comments",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ah.source_date AS Time,\n  COUNT(DISTINCT ct.id) AS \"# Comments\"\nFROM\n  news_meta_data.article_header ah\n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\n  INNER JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  INNER JOIN news_meta_data.comment ct ON ab.id = ct.article_body_id\n  INNER JOIN news_meta_data.analyzer1_result a1r ON ct.id = a1r.comment_id\n  LEFT JOIN \n    (\n    SELECT\n      1 AS id,\n      'Ensemble' AS nlp_model\n    UNION ALL\n    SELECT\n      2 AS id,\n      'Multilanguage Bert' AS nlp_model\n    UNION ALL\n    SELECT\n      3 AS id,\n      'German Bert' AS nlp_model\n    ) nlp ON a1r.sub_id = nlp.id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet_right)\n  AND nlp.nlp_model = '$nlp_model_right'\n  AND ct.body ILIKE '% $comment_key_word_right%'\nGROUP BY\n  ah.source_date\nORDER BY\n  1"
    }
   ]
  },
  { "title": "Comperative Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Difference (Left and Right) Sentiment Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "WITH comment_1 AS (\nSELECT\n  ah.source_date AS Time,\n  --SUM(a1r.sentiment_value/ (a1r.error_value * a1r.error_value )) / SUM(1 / (a1r.error_value * a1r.error_value)) AS \"Sentiment1 Error Weighted\",\n  AVG(a1r.sentiment_value) AS \"Sentiment Simple Average\"\nFROM\n  news_meta_data.article_header ah\n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\n  INNER JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  INNER JOIN news_meta_data.comment ct ON ab.id = ct.article_body_id\n  INNER JOIN news_meta_data.analyzer1_result a1r ON ct.id = a1r.comment_id\n  LEFT JOIN \n    (\n    SELECT\n      1 AS id,\n      'Ensemble' AS nlp_model\n    UNION ALL\n    SELECT\n      2 AS id,\n      'Multilanguage Bert' AS nlp_model\n    UNION ALL\n    SELECT\n      3 AS id,\n      'German Bert' AS nlp_model\n    ) nlp ON a1r.sub_id = nlp.id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet_left)\n  AND nlp.nlp_model = '$nlp_model_left'\n  AND ct.body ILIKE '% $comment_key_word_left%'\nGROUP BY\n  ah.source_date\n),\ncomment_2 AS (\nSELECT\n  ah.source_date AS Time,\n  --SUM(a1r.sentiment_value/ (a1r.error_value * a1r.error_value )) / SUM(1 / (a1r.error_value * a1r.error_value)) AS \"Sentiment1 Error Weighted\",\n  AVG(a1r.sentiment_value) AS \"Sentiment Simple Average\"\nFROM\n  news_meta_data.article_header ah\n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\n  INNER JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  INNER JOIN news_meta_data.comment ct ON ab.id = ct.article_body_id\n  INNER JOIN news_meta_data.analyzer1_result a1r ON ct.id = a1r.comment_id\n  LEFT JOIN \n    (\n    SELECT\n      1 AS id,\n      'Ensemble' AS nlp_model\n    UNION ALL\n    SELECT\n      2 AS id,\n      'Multilanguage Bert' AS nlp_model\n    UNION ALL\n    SELECT\n      3 AS id,\n      'German Bert' AS nlp_model\n    ) nlp ON a1r.sub_id = nlp.id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet_right)\n  AND nlp.nlp_model = '$nlp_model_right'\n  AND ct.body ILIKE '% $comment_key_word_right%'\nGROUP BY\n  ah.source_date\n)\n\nSELECT\n  c1.time AS time,\n  c1.\"Sentiment Simple Average\" - c2.\"Sentiment Simple Average\" AS \"Delta Sentiment Simple Average\"\nFROM\n  comment_1 c1\n  INNER JOIN comment_2 c2 ON c1.time = c2.time\nWHERE \n  $__timeFilter(c1.time) \nORDER BY \n  1\n\n"
    }
   ]
  },
  {
   "title": "Comment Ratio",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "WITH comment_1 AS (\nSELECT\n  ah.source_date AS Time,\n  COUNT(DISTINCT ct.id) AS \"# Comments\"\nFROM\n  news_meta_data.article_header ah\n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\n  INNER JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  INNER JOIN news_meta_data.comment ct ON ab.id = ct.article_body_id\n  INNER JOIN news_meta_data.analyzer1_result a1r ON ct.id = a1r.comment_id\n  LEFT JOIN \n    (\n    SELECT\n      1 AS id,\n      'Ensemble' AS nlp_model\n    UNION ALL\n    SELECT\n      2 AS id,\n      'Multilanguage Bert' AS nlp_model\n    UNION ALL\n    SELECT\n      3 AS id,\n      'German Bert' AS nlp_model\n    ) nlp ON a1r.sub_id = nlp.id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet_left)\n  AND nlp.nlp_model = '$nlp_model_left'\n  AND ct.body ILIKE '% $comment_key_word_left%'\nGROUP BY\n  ah.source_date\n),\ncomment_2 AS (\nSELECT\n  ah.source_date AS Time,\n  COUNT(DISTINCT ct.id) AS \"# Comments\"\nFROM\n  news_meta_data.article_header ah\n  LEFT JOIN news_meta_data.source_header sh ON ah.source_id = sh.id\n  INNER JOIN news_meta_data.article_body ab ON ah.id = ab.article_id\n  INNER JOIN news_meta_data.comment ct ON ab.id = ct.article_body_id\n  INNER JOIN news_meta_data.analyzer1_result a1r ON ct.id = a1r.comment_id\n  LEFT JOIN \n    (\n    SELECT\n      1 AS id,\n      'Ensemble' AS nlp_model\n    UNION ALL\n    SELECT\n      2 AS id,\n      'Multilanguage Bert' AS nlp_model\n    UNION ALL\n    SELECT\n      3 AS id,\n      'German Bert' AS nlp_model\n    ) nlp ON a1r.sub_id = nlp.id\nWHERE\n  $__timeFilter(ah.source_date) \n  AND sh.source IN ($news_outlet_right)\n  AND nlp.nlp_model = '$nlp_model_right'\n  AND ct.body ILIKE '% $comment_key_word_right%'\nGROUP BY\n  ah.source_date\n)\n\nSELECT\n  c1.time AS time,\n  c1.\"# Comments\"/c2.\"# Comments\"::NUMERIC AS \"Comment1-Comment2-Ratio\"\nFROM\n  comment_1 c1\n  INNER JOIN comment_2 c2 ON c1.time = c2.time\nWHERE\n  $__timeFilter(c1.time) \nORDER BY\n  1"
    }
   ]
  }
 ]
}